apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-install-application.yaml
  - operator-lifecycle-manager-application.yaml
  - kuadrant-applicationset.yaml
