apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-hub
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    path: manifests/observability-hub/k8s
    # repoURL: https://github.com/kuadrant/deployment
    # targetRevision: HEAD
    repoURL: https://github.com/roivaz/kuadrant-deployment
    targetRevision: ha-setup
  syncPolicy:
    automated:
      selfHeal: true
