- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: grafana-istio-workload
    configMap:
     defaultMode: 420
     name: grafana-istio-workload
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: grafana-mgc-metrics
    configMap:
     defaultMode: 420
     name: grafana-mgc-metrics
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: grafana-platform-eng
    configMap:
     defaultMode: 420
     name: grafana-platform-eng
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: grafana-app-developer
    configMap:
     defaultMode: 420
     name: grafana-app-developer
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: grafana-business-user
    configMap:
     defaultMode: 420
     name: grafana-business-user
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: grafana-istio-workload
    mountPath: /grafana-dashboard-definitions/0/grafana-istio-workload
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: grafana-mgc-metrics
    mountPath: /grafana-dashboard-definitions/0/grafana-mgc-metrics
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: grafana-platform-eng
    mountPath: /grafana-dashboard-definitions/0/grafana-platform-eng
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: grafana-app-developer
    mountPath: /grafana-dashboard-definitions/0/grafana-app-developer
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: grafana-business-user
    mountPath: /grafana-dashboard-definitions/0/grafana-business-user
